package PasteBin::Model::PasteDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Paste::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:db/pastebin.db',
        user => '',
        password => '',
    }
);

=head1 NAME

PasteBin::Model::PasteDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PasteBin>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Paste::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

Edward

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
